name: Add comment
on:
  pull_request:
    types: [ labeled ]
jobs:
  add-comment:
    if: github.event.label.name == 'bors r+'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Add comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            bors r+
