name: Git Push
on:
  workflow_dispatch:

jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Modifiy the specific files using scripts
        run: |
          sed -i -E \"/SNAPSHOT/s/version.*/version '99.99.99-SNAPSHOT'/g\" build.gradle
      
      - name: Commit and push changes
        run: |
          git config --global user.name "csrawat"
          git config --global user.email "cs215100@gmail.com"
          git add -A
          git commit -m "commit message"
          git push
