name: Java CI with Gradle

on:
  pull_request:
    branches: "*"
    types: [labeled, synchronize, edited, reopened]
    
permissions:
  contents: read
  
jobs:
  build:
    name: Java CI with Gradle
    
    if: contains(github.event.pull_request.labels.*.name, 'build')
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew clean build testClasses -x test
