name: Java CI with Gradle

on:
  pull_request_target:
    branches: "*"
    types: [labeled, synchronize, edited, reopened]
    
permissions:
  contents: read
  
jobs:
  build:
    name: Java CI with Gradle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build when label added
      if: contains(github.event.pull_request.labels.*.name, 'build')
      run: ./gradlew clean build testClasses -x test

    - name: Fail when label not added
      if: contains(github.event.pull_request.labels.*.name, 'build') == false
      run: exit 1
      
    - name: Notify slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: build-bot
        status: SUCCESS
        color: good

    - name: Notify slack fail
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: build-bot
        status: FAILED
        color: danger

