name: Publish

on:
  push:
    branches: "master"
    
permissions:
  contents: read
  
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Publish
      run: |
        chmod +x publish.sh
        ./publish.sh
        MY_STRING=$(cat version_file)
        printf "$MY_STRING"
        echo "MY_STRING<<EOF" >> $GITHUB_ENV
        echo "$MY_STRING" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      id: version
      shell: bash
  
  notify:
    name: Notify
    if: "!contains(${{ env.MY_STRING }}, 'no module is published.')"
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: 'C0418TCEH8B'
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.head_commit.url }}\n${{ env.MY_STRING }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
