name: PUBLISH NEW

on:
  pull_request:
    types:
      - closed

jobs:
  pre-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Pre Publish
      run: |
        echo 'Pre Publish'
      shell: bash
  publish:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'PUBLISH')) }}
    runs-on: ubuntu-latest
    steps:
    - name: Publish New
      run: |
        echo 'Publish New'
      shell: bash
