name: Publish

on:
  push:
    branches: "master"
    
permissions:
  contents: read
  
jobs:
  build:
    name: Publish
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Publish
      run: |
        chmod +x publish.sh
        ./publish.sh
      shell: bash
