name: Publish

on:
  push:
    branches: "master"
    
permissions:
  contents: read
  
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Publish
      run: |
        chmod +x publish.sh
        ./publish.sh
        MY_STRING=$(cat version_file)
        echo "MY_STRING<<EOF" >> $GITHUB_ENV
        echo "$MY_STRING" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
#        CHANGELOG="${CHANGELOG//'%'/'%25'}"
#        CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
#        CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
#        echo "::set-output name=changeLog::$CHANGELOG"
      id: version
      shell: bash
      
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.21.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: 'C041ZASDH16'
        # For posting a simple plain text message
#        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.head_commit.url }}\n${{ steps.version.outputs.changeLog }}"
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.head_commit.url }}\n${{ env.MY_STRING }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
