name: PUBLISH

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Publish
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Publish
      run: |
        CHANGELOG=$(cat results.txt)
        printf "$CHANGELOG"
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        echo "$CHANGELOG" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      id: version
      shell: bash
      
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: 'C0418TCEH8B'
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.head_commit.url }}\n${{ env.MY_STRING }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
